//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tc_yabanci_birlesik.dogrulama {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS", ConfigurationName="dogrulama.KPSPublicYabanciDogrulaSoap")]
    public interface KPSPublicYabanciDogrulaSoap {
        
        // CODEGEN: Generating message contract since element name Ad from namespace http://tckimlik.nvi.gov.tr/WS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tckimlik.nvi.gov.tr/WS/YabanciKimlikNoDogrula", ReplyAction="*")]
        tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse YabanciKimlikNoDogrula(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tckimlik.nvi.gov.tr/WS/YabanciKimlikNoDogrula", ReplyAction="*")]
        System.Threading.Tasks.Task<tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse> YabanciKimlikNoDogrulaAsync(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YabanciKimlikNoDogrulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YabanciKimlikNoDogrula", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequestBody Body;
        
        public YabanciKimlikNoDogrulaRequest() {
        }
        
        public YabanciKimlikNoDogrulaRequest(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class YabanciKimlikNoDogrulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long KimlikNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> DogumGun;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> DogumAy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int DogumYil;
        
        public YabanciKimlikNoDogrulaRequestBody() {
        }
        
        public YabanciKimlikNoDogrulaRequestBody(long KimlikNo, string Ad, string Soyad, System.Nullable<int> DogumGun, System.Nullable<int> DogumAy, int DogumYil) {
            this.KimlikNo = KimlikNo;
            this.Ad = Ad;
            this.Soyad = Soyad;
            this.DogumGun = DogumGun;
            this.DogumAy = DogumAy;
            this.DogumYil = DogumYil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YabanciKimlikNoDogrulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YabanciKimlikNoDogrulaResponse", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponseBody Body;
        
        public YabanciKimlikNoDogrulaResponse() {
        }
        
        public YabanciKimlikNoDogrulaResponse(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class YabanciKimlikNoDogrulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool YabanciKimlikNoDogrulaResult;
        
        public YabanciKimlikNoDogrulaResponseBody() {
        }
        
        public YabanciKimlikNoDogrulaResponseBody(bool YabanciKimlikNoDogrulaResult) {
            this.YabanciKimlikNoDogrulaResult = YabanciKimlikNoDogrulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KPSPublicYabanciDogrulaSoapChannel : tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KPSPublicYabanciDogrulaSoapClient : System.ServiceModel.ClientBase<tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap>, tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap {
        
        public KPSPublicYabanciDogrulaSoapClient() {
        }
        
        public KPSPublicYabanciDogrulaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KPSPublicYabanciDogrulaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KPSPublicYabanciDogrulaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KPSPublicYabanciDogrulaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap.YabanciKimlikNoDogrula(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest request) {
            return base.Channel.YabanciKimlikNoDogrula(request);
        }
        
        public bool YabanciKimlikNoDogrula(long KimlikNo, string Ad, string Soyad, System.Nullable<int> DogumGun, System.Nullable<int> DogumAy, int DogumYil) {
            tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest inValue = new tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest();
            inValue.Body = new tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequestBody();
            inValue.Body.KimlikNo = KimlikNo;
            inValue.Body.Ad = Ad;
            inValue.Body.Soyad = Soyad;
            inValue.Body.DogumGun = DogumGun;
            inValue.Body.DogumAy = DogumAy;
            inValue.Body.DogumYil = DogumYil;
            tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse retVal = ((tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap)(this)).YabanciKimlikNoDogrula(inValue);
            return retVal.Body.YabanciKimlikNoDogrulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse> tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap.YabanciKimlikNoDogrulaAsync(tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest request) {
            return base.Channel.YabanciKimlikNoDogrulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaResponse> YabanciKimlikNoDogrulaAsync(long KimlikNo, string Ad, string Soyad, System.Nullable<int> DogumGun, System.Nullable<int> DogumAy, int DogumYil) {
            tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest inValue = new tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequest();
            inValue.Body = new tc_yabanci_birlesik.dogrulama.YabanciKimlikNoDogrulaRequestBody();
            inValue.Body.KimlikNo = KimlikNo;
            inValue.Body.Ad = Ad;
            inValue.Body.Soyad = Soyad;
            inValue.Body.DogumGun = DogumGun;
            inValue.Body.DogumAy = DogumAy;
            inValue.Body.DogumYil = DogumYil;
            return ((tc_yabanci_birlesik.dogrulama.KPSPublicYabanciDogrulaSoap)(this)).YabanciKimlikNoDogrulaAsync(inValue);
        }
    }
}
